from random import shuffle, sample

integradores = "	AFE Construtora	"	, "	AIV MEIO AMBIENTE E ENERGIA	"	, "	AN LOPES	"	, "	ARFRIO-TECH	"	, "	Art & Moda	"	, "	ARTLUZ	"	, "	Atohn Energias Renováveis	"	, "	Barbosa & Costa	"	, "	Betel Solar Serviços Ltda	"	, "	BIADORA	"	, "	BRESAN SERVIÇOS DE ENGENHARIA	"	, "	Cabral Energia Solar	"	, "	CASA DAS MOTOSSERRAS	"	, "	CLEAN LUX DO BRASIL	"	, "	Conexão Solar	"	, "	Confiança Solar	"	, "	CRESOL ENERGIA SOLAR	"	, "	D&s Climatizacao	"	, "	DJL SOLUÇÕES	"	, "	DMG Solar	"	, "	Duarte Elétrica	"	, "	ELÉTRICA TOTAL	"	, "	ELETRO LIMA	"	, "	ENERGEM	"	, "	Energy Systems	"	, "	ES Fotovoltaico Energia Solar	"	, "	exata solar engenharia	"	, "	FACE NORTE	"	, "	FASE SOLUÇÕES ELÉTRICAS E ENERGIA SOLAR	"	, "	Ferreira & Bravo	"	, "	G&A Reparos	"	, "	Giselle Alonso Costa	"	, "	GREEN CONDOMÍNIOS	"	, "	Grupo Impacto	"	, "	HCL	"	, "	HENESOL	"	, "	Hidra Solar	"	, "	Ilumine Energia Solar	"	, "	INVESTSOL ENERGIA SOLAR	"	, "	JD SOLUÇÕES INTELIGENTES	"	, "	JOSE ADELSON DOS SANTOS	"	, "	JRLP	"	, "	Luana Camelo	"	, "	Lucas das Silva Pascoal Engenharia	"	, "	LUMNIRIO SOLUÇÕES FOTOVOLTAICAS	"	, "	MITRA VOLT	"	, "	Montenegro & Correa	"	, "	MP Imported	"	, "	MS SOLAR	"	, "	MZ SOLAR	"	, "	NATAL ENERGY	"	, "	NEXUSS - Sustentabilidade e Energias	"	, "	OAK Energia	"	, "	OMNI ENGENHARIA	"	, "	ONsTECH	"	, "	Orion Solar	"	, "	Parra Soluções em Energia	"	, "	Plemax Energia Solar	"	, "	Pomponet	"	, "	PRIMMOS SOLAR SOLUÇÕES ELÉTRICAS	"	, "	Prisma Comercio	"	, "	PRO ELÉTRICA	"	, "	PROENG INSTALAÇÃO E MANUTENÇÃO ELÉTRICA	"	, "	Providencia Solar	"	, "	RD Energia Solar	"	, "	REDUZA ENERGIA	"	, "	ROOF SOLAR	"	, "	Samal Engenharia & Energia Solar	"	, "	SANDRO CLAUSMIR GONTIJO	"	, "	SBB	"	, "	SEE ENERGIA LTDA	"	, "	SIFASE ELÉTRICA	"	, "	Sol Nascente Energia Solar	"	, "	SOLAR AGEFLEX	"	, "	Solara Energia	"	, "	Solarium Energia	"	, "	SOLI TECNOLOGIA	"	, "	ST ECOX	"	, "	Total Solar	"	, "	VITAL ELETRONICA	"	, "	VITAL ENERGIA SOLAR	"	, "	VIXSOL – ENERGIA SOLAR	"	, "	vjautomação	"	, "	Volt Engenharia	"	, "	WM Engenharia Ltda	"	, "	WorkSun Energia Solar	"	, "	WP Informática	"	, "	Energy +	"	, "	Refriar Solar	"	, "	ODONTOTEC	"	, "	MD ENERGIA SOLAR	"	, "	Crefinorte	"	, "	José Rene Pierobom Eirelli	"	, "	Life Solar Eletricidade e Automação	"	, "	BRM Automação 	"	, "	DAYTELECOM	"	, "	Mauricio Yoshiharu Suzuki	"	, "	M & M INSTALADORA ELETRO ELETRONICA	"	, "	STIIL SOLAR	"	, "	Andrade & Oliveira	"	, "	Conceito Solar	"	, "	S8 Energia Solar	"	, "	M.V.L EMPREENDIMENTOS IMOBILIARIOS EIRELI	"	, "	Solar System Solution	"	, "	Solar Tech Sistemas Fotovoltaicos	"	, "	Omega Consultoria	"	, "	Pix Telecomunicações Ltda	"	, "	SOLARTECH 	"	, "	William Rodrigo de Souza - WRS	"	, "	COPAN ENGENHARIA	"	, "	CHUNA ENERGIA SOLAR	"	, "	ECOSOL ENERGIA SOLAR	"	, "	SOL NORTE ENERGIA SOLAR	"	, "	Alternativa Verde Solar	"	, "	HR Espaço Solar	"	, "	HIKARI ENERGIA SOLAR 	"	,
aleatorio = sample(integradores,116)
pedro = aleatorio[0:39]
marcio = aleatorio[40:78]
victor = aleatorio[79:]

print(f'A carteira do Pedro é:{pedro}\n'
      f'A carteira do Marcio é: {marcio}\n'
      f'A carteira do Victor é: {victor}')